### ISSUE TITLE
Hey :) Un read the doc prevu ?

### ISSUE THREAD

**Issue by PurpleBabar** [MathRobin/livre-blanc-seo#21]
Salut :) 

As tu prévu de faire un read the docs pour ce projet ? histoire de mettre en forme tout ca dans un format reader friendly ? :smile: 

Merci :)

**Comment by MathRobin** [comment]
Tu peux nous en dire un peu plus ? Je suis pas sûr d'avoir saisi

**Comment by PurpleBabar** [comment]
Hey :)  je voulais savoir si tu avais prevu de laisser le document tel quel sur github ou si tu comptais utiliser read the docs pour en faire une doc plus sympa a lire :)

**Comment by MathRobin** [comment]
Nope, ça restera sur Github. J'ai peur que ça finisse par devenir un document purement à titre de consommation et que les lecteurs en oublient qu'il est avant tout participatif.

Ceci dit, tu soulèves un point important qu'est la lisibilité. Et ça il y a sûrement de grosses choses potentielles à faire tout en restant sur Github. Déjà je vais commencer par découper le gros readme en plusieurs fichiers pour en faciliter la lecture. Seule la table des matières resterait dans le readme

**Comment by PurpleBabar** [comment]
Un github io ? peut etre ? :)

**Comment by MathRobin** [comment]
Complètement bonne idée

**Comment by PurpleBabar** [comment]
:smiley:  Si tu as besoin d'aide n'hesites pas :smiley:

**Comment by MathRobin** [comment]
Yep, j'ai mis le label "help wanted" sur cette issue, toute aide est la bienvenue. N'hésite à faire des suggestions, proposer des liens sur comment générer un github.io à partir de markdown ou même carrément à dev un truc et le proposer en PR. Toute proposition est la bienvenue, Même si ce dépôt est dans mon espace github, il faut absolument que ce projet ne soit pas le mien et reste collaboratif/participatif :)

**Comment by PurpleBabar** [comment]
Super :)

**Comment by PurpleBabar** [comment]
Ce lien
https://help.github.com/articles/creating-pages-with-the-automatic-generator/
et ce lien :
https://pages.github.com/
devraient t'aider, et je ferai une pull request si j'ai le temps vendredi ou ce weekend :)

**Comment by MathRobin** [comment]
Top, déjà merci pour ces liens. Et j'espère que t'auras le temps, ce projet a besoin de toutes les bonnes volontés^^

**Comment by PurpleBabar** [comment]
Je vais faire en sorte d'en trouver alors ;)

**Comment by PurpleBabar** [comment]
https://pages.github.com/ Ce lien explique qu'il faudra une fois ma pull request soumise, changer les paramatres du repo pour que github sache ou aller taper :)
Je te fais ma pull request demain :) ++

**Comment by MathRobin** [comment]
C'est quoi le procédé pour générer le site que tu as fait ? Tu saurais le documenter ?

**Comment by PurpleBabar** [comment]
Hey :) Oui je pourrais le documenter, voir meme créer un process complet (j'ai fait un bonne partie a la main pour l'instant, mais que j'aurais pu automatiser)

**Comment by MathRobin** [comment]
Ca serait immensément génial de ta part :)

**Comment by PurpleBabar** [comment]
Ok :) je m'y met des que jai le temps :)

**Comment by MathRobin** [comment]
T'es génial ! :)

**Comment by PurpleBabar** [comment]
Hey :)
Jai a moitié automatisé le process avec un fichier gulp :) tout est dispo ici https://elephantly.github.io/markdown-converter/

Je vais updater le projet avec le site a jour du coup :) je te fais une pull request de suite :)

++ 😃

**Comment by PurpleBabar** [comment]
Du coup je te laisse updater le repo avec un CONTRIBUTING.md enf ait la procedure, c'est faire un ```npm install``` dans le repo, ensuite faire un ```gulp convert``` ensuite il faut decouper les index.njk en block (intro, menu, content) et puis faire un ```gulp compile```. et voila :) le site est pret, plus qu'a pusher :)

**Comment by MathRobin** [comment]
Je viens de faire le merge. Sacré boulot ! Je te remercie pour cette énorme contribution. Je testerai tout à l'heure, c'est moins simple de faire du gulp depuis un téléphone.

**Comment by PurpleBabar** [comment]
XD oui effectivement du gulp sur un telephone cest pas simple 😃
