### ISSUE TITLE
Générer une table des matières

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/livre-blanc-seo#7]
Sinon ça va vite devenir non navigable (ça l'est déjà en fait)
https://github.com/ekalinin/github-markdown-toc

**Comment by startupz** [comment]
#8

**Comment by MathRobin** [comment]
De rien, j'ai découvert hier soir en fouillant sur le net. Je n'avais jamais eu besoin de générer une toc. Je regarde ta pull request asap
